#!/usr/bin/env Rscript

############################################## About Author #########################################
# Created by: Alsamman M. Alsamman                                                                  #
# Emails: smahmoud [at] ageri.sci.eg or A.Alsamman [at] cgiar.org or SammanMohammed [at] gmail.com  #
# License: MIT License - https://opensource.org/licenses/MIT                                        #
# Disclaimer: The script comes with no warranty, use at your own risk                               #
# This script is not intended for commercial use                                                    #
#####################################################################################################

# What is this system linux or windows
system<-Sys.info()[1]
# if system is windows then change the path separator
if (system=="Windows") {
  pathSeparator<-"\\"
} else {
  pathSeparator<-"/"
}

#######################################################################################


args = commandArgs(trailingOnly=TRUE)

# test if there is at least one argument: if not, return an error
if (length(args)==0) {
  stop("At least one argument must be supplied (input file).n", call.=FALSE)
} #else if (length(args)==1) {
  # default output file
  #args[2] = "out.txt"
#}

if (length(args) < 3) {
  print(paste("Usage: Rscript plot_GWAS_GEMMA.r <gwasfile> <traitName> <ResultFolder> <fdrcutoff> <qthreshold> <chrTable>",sep=""))
  quit()
}

# plot PCA generated by PLINK
# loading libraries
library(ggplot2)
library(ggpubr)

# input file
# eigenvecFile = args[1]
# eigenvalFile = args[2]

pcaFolder="/home/samman/Documents/publishing/kahled_hashem_Goat/PCA"

eigenvecFile = paste(pcaFolder,  "PCA.eigenvec", sep="/")
eigenvalFile = paste(pcaFolder,  "PCA.eigenval", sep="/")
metaFile="/home/samman/Documents/publishing/kahled_hashem_Goat/samples_Meta.tsv"


# read eigenvec file
eigenvec = read.table(eigenvecFile, header=FALSE, sep="", row.names=1)
# read eigenval file
eigenval = read.table(eigenvalFile, header=FALSE, sep="")
# read meta file
meta = read.table(metaFile, header=TRUE, sep="\t", row.names=1)

# remove the first column
eigenvec = eigenvec[,-1]
# add column names
colnames(eigenvec) = paste("PC", 1:ncol(eigenvec), sep="")
# merge the eigenvec and meta
eigenvec = merge(eigenvec, meta, by=0)


# plot the PCA
pcaPlot = ggplot(eigenvec, aes(x=PC1, y=PC2, color=Country)) +
  geom_point(size=3) +
theme_minimal() + labs(title="PCA", x="PC1", y="PC2")# fill by country
# calculate the percentage of variance explained by each PC
variance = eigenval$V1/sum(eigenval$V1)*100
# add the percentage of variance explained by each PC on the x-axis and y-axis by changing the titles


pcaPlot = pcaPlot + labs(title="PCA", x=paste("PC1 (", round(variance[1], 2), "%)", sep=""), y=paste("PC2 (", round(variance[2], 2), "%)", sep=""))


pcaPlot

ggsave(paste(pcaFolder, "PCA_plot.pdf", sep="/"), pcaPlot, width=20, height=20, units="cm")
